### ISSUE TITLE
3.9

### ISSUE THREAD

**Issue by sammarland-rh** [RedHat-EMEA-SSA-Team/hetzner-ocp#9]
Are there any plans to update this repo to openshift 3.9?

**Comment by tahonen** [comment]
In progress...3.9 and also CNS.

**Comment by tahonen** [comment]
Also adding cri-o as runtime

**Comment by sammarland-rh** [comment]
Great news. Happy to test if you need testers.

**Comment by tahonen** [comment]
There is branch 39-crio-cns available for testing...some changes in ...vars/guests.yml. check example file. Will later update readme
